### ISSUE TITLE
how to fold the documentation strings

### ISSUE THREAD

**Issue by geraldodev** [gberenfield/cljfold.vim#1]
it would be nice if we could fold the documentation strings. The 1st line of documentation could remain as a tittle and the rest would be folded.

When you have a very documented library, it can occupy more space than code.

Regards,

Geraldo

**Comment by gberenfield** [comment]
Not something I'm really after.. pull requests welcome howerver. For something like what you're suggesting, marginalia etc. I find useful. Or for a more vim-esque solution, you may want to look at [ctags](http://blog.stwrt.ca/2012/10/31/vim-ctags)
