### ISSUE TITLE
Folding of forms not separated by empty line?

### ISSUE THREAD

**Issue by Gonzih** [gberenfield/cljfold.vim#2]
Hi, is it possible to introduce folding for some forms that are not separated by empty line?

Example is defn and ann forms (core.typed).

Thanks!

**Comment by gberenfield** [comment]
Sorry I don't quite understand. It's folding fine for me on defn with no linespaces in-between.
Can you please provide a specific example?

**Comment by Gonzih** [comment]
Sorry if it's confusing. Here is screenshot 
![image](https://cloud.githubusercontent.com/assets/266275/4810561/2be19ad2-5eb4-11e4-8911-6debb4400fd3.png)

**Comment by gberenfield** [comment]
So you want 1-line items folded? Honestly it's not something I'm personally after. But if you want to make a patch with optional functionality for it (based on a new flag option), that's fine.

**Comment by Gonzih** [comment]
So one lines are not folded by default? Then it makes sense. Thanks!

—
Regards,
Max
